[target.aarch64-linux-android]
rustflags = [
  "-C",
  "link-arg=-Wl,-z,max-page-size=16384",
  "-C",
  "link-arg=-Wl,-soname,librhythm_ffi.so",
]

[target.armv7-linux-androideabi]
rustflags = [
  "-C",
  "link-arg=-Wl,-z,max-page-size=16384",
  "-C",
  "link-arg=-Wl,-soname,librhythm_ffi.so",
]

[target.x86_64-linux-android]
rustflags = [
  "-C",
  "link-arg=-Wl,-z,max-page-size=16384",
  "-C",
  "link-arg=-Wl,-soname,librhythm_ffi.so",
]
